### ISSUE TITLE
Describe installation of the client in the README.md

### ISSUE THREAD

**Issue by oleg68** [FoundationDB/fdb-joshua#8]
I've downloaded fdb-jushua.

I've installed fdb python bindings with
```
pip install fdb
```

When I try to run a client command, I always receive an error:

```
[oleg@oleg2 FdbJoshua]$ python3 -m joshua.joshua list
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/oleg/work/fdb/FdbJoshua/joshua/joshua.py", line 22, in <module>
    from . import joshua_model
  File "/home/oleg/work/fdb/FdbJoshua/joshua/joshua_model.py", line 42, in <module>
    fdb.api_version(520)
AttributeError: module 'fdb' has no attribute 'api_version'
```

What have I missed?

**Comment by johscheuer** [comment]
I'm not to familiar with Joshua. Normally the Python lib also needs the FDB client package installed (https://www.foundationdb.org/download).

**Comment by oleg68** [comment]
I have foundationdb-client installed on my machine. But joshua cleint does not work

**Comment by jzhou77** [comment]
Is `pip` installing `fdb` python package in the correct location? Can you check if `fdb` package is at library path of python 3.9 (the version you have)?

**Comment by oleg68** [comment]
The necessary client installation steps are:

1. Install foundationdb-clients from https://www.foundationdb.org/download/
2. Install wheel with pip
3. install foundationdb with pip
4. go to the fdb-joshua directory
5. run any joshua commands

In my case I missed (2) so fdb was no installed correctly
